name: Build and Deploy
on:
  # run when the trunk branch is updated
  push:
    branches:
      - trunk

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && github.repository == 'ZenesisUK/zx.ui.accordion'"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Build and Deploy
        run: |
          ./.github/workflows/build-website.sh "${{ secrets.WEBSITE_DEPLOY_KEY }}"
